# Run package tests using SQL Server. Uses pre-built image; expects CDM5_SQL_SERVER_* secrets.
SQL_SERVER_DRIVER
CDM5_SQL_SERVER_SERVER
CDM5_SQL_SERVER_CDM_DATABASE
CDM5_SQL_SERVER_USER
CDM5_SQL_SERVER_PASSWORD
CDM5_SQL_SERVER_PORT
CDM5_SQL_SERVER_CDM_SCHEMA
CDM5_SQL_SERVER_SCRATCH_SCHEMA
on:
  push:
    branches: [main, master, test, develop]
  pull_request:
    branches: [main, master, develop]

name: Tests (PostgreSQL)

jobs:
  test-postgres:
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-eu-dev/examplestudy-base:latest
      env:
        SQL_SERVER_DRIVER:              ${{ secrets.SQL_SERVER_DRIVER}}
        CDM5_SQL_SERVER_SERVER:         ${{ secrets.CDM5_SQL_SERVER_SERVER}}
        CDM5_SQL_SERVER_CDM_DATABASE:   ${{ secrets.CDM5_SQL_SERVER_CDM_DATABASE}}
        CDM5_SQL_SERVER_USER:           ${{ secrets.CDM5_SQL_SERVER_USER}}
        CDM5_SQL_SERVER_PASSWORD:       ${{ secrets.CDM5_SQL_SERVER_PASSWORD}}
        CDM5_SQL_SERVER_PORT:           ${{ secrets.CDM5_SQL_SERVER_PORT}}
        CDM5_SQL_SERVER_CDM_SCHEMA:     ${{ secrets.CDM5_SQL_SERVER_CDM_SCHEMA}}
        CDM5_SQL_SERVER_SCRATCH_SCHEMA: ${{ secrets.CDM5_SQL_SERVER_SCRATCH_SCHEMA}}

    name: Sqlserver test

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Install packages and prepare data
        run: |
          install.packages("devtools", repos = "https://cloud.r-project.org/")
          install.packages("remotes", repos = "https://cloud.r-project.org/")
          install.packages("testthat", repos = "https://cloud.r-project.org/")
        shell: Rscript {0}

      - name: Run tests (SQL Server)
        run: R -e 'devtools::install(); devtools::test(filter = "sqlserver")'
