# Run package tests using PostgreSQL. Uses pre-built image; expects CDM5_POSTGRESQL_* secrets.
on:
  push:
    branches: [main, master, test, develop]
  pull_request:
    branches: [main, master, develop]

name: Tests (PostgreSQL)

jobs:
  test-postgres:
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-eu-dev/examplestudy-base:latest
      env:
        CDM5_POSTGRESQL_USER:           ${{ secrets.CDM5_POSTGRESQL_USER }}
        CDM5_POSTGRESQL_PORT:           ${{ secrets.CDM5_POSTGRESQL_PORT }}
        CDM5_POSTGRESQL_PASSWORD:       ${{ secrets.CDM5_POSTGRESQL_PASSWORD }}
        CDM5_POSTGRESQL_SERVER:         ${{ secrets.CDM5_POSTGRESQL_SERVER }}
        CDM5_POSTGRESQL_HOST:           ${{ secrets.CDM5_POSTGRESQL_HOST }}
        CDM5_POSTGRESQL_DBNAME:         ${{ secrets.CDM5_POSTGRESQL_DBNAME }}
        CDM5_POSTGRESQL_CDM_SCHEMA:     ${{ secrets.CDM5_POSTGRESQL_CDM_SCHEMA }}
        CDM5_POSTGRESQL_SCRATCH_SCHEMA: ${{ secrets.CDM5_POSTGRESQL_SCRATCH_SCHEMA }}
        GITHUB_PAT:                     ${{ secrets.GITHUB_TOKEN }}

    name: Postgres test

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Install packages and prepare data
        run: |
          install.packages("devtools", repos = "https://cloud.r-project.org/")
          install.packages("remotes", repos = "https://cloud.r-project.org/")
          install.packages("testthat", repos = "https://cloud.r-project.org/")
        shell: Rscript {0}

      - name: Run tests (PostgreSQL)
        run: R -e 'devtools::install(); devtools::test(filter = "PostgreSQL")'
